version: "3.0"
services:
  kong-database:
    image: postgres:9.6
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_KONG_DB}
    ports:
      - 5432:5432
    networks:
      - kong-net

  kong-migrate:
    image: kong:2.3.3
    restart: on-failure
    command: kong migrations bootstrap
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=${PG_KONG_DB}
      - KONG_PG_USER=${PG_USER}
      - KONG_PG_PASSWORD=${PG_PASSWORD}
    depends_on:
      - kong-database
    networks:
      - kong-net

  kong:
    image: kong:2.3.3
    restart: always
    environment:
      - KONG_LOG_LEVEL=debug
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=${PG_KONG_DB}
      - KONG_PG_USER=${PG_USER}
      - KONG_PG_PASSWORD=${PG_PASSWORD}
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    depends_on:
      - kong-migrate
      - kong-database
    networks:
      - kong-net

  konga-prepare:
    image: pantsel/konga:0.14.9
    command: "-c prepare -a postgres -u postgresql://${PG_USER}:${PG_PASSWORD}@kong-database:5432/${PG_KONGA_DB}"
    networks:
      - kong-net
    restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong-database

  konga:
    image: pantsel/konga:0.14.9
    restart: on-failure
    networks:
      - kong-net
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=kong-database
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASSWORD}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - DB_DATABASE=${PG_KONGA_DB}
      - NODE_ENV=production
    depends_on:
      - kong-database
    ports:
      - "1337:1337"

networks:
  kong-net:
    driver: bridge
